Add doxygen detection and conditionnal apidoc generation

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS AWK INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE RANLIB ac_ct_RANLIB AR CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP LIBOBJS PKG_CONFIG XML2_CONFIG GTK_CONFIG LEX LEXLIB LEX_OUTPUT_ROOT YACC XMLRPC_CONFIG CXX CXXFLAGS ac_ct_CXX build build_cpu build_vendor build_os host host_cpu host_vendor host_os HOST_TARGET ARFLAGS LDLIBS TSP_BASE ENABLED_TSP_TARGET BB SHAREDLIB_ENABLED GL_OK GLUT_OK SCRIPT_BINDING TSPCONSUMER XML2_CONFIG_USER XMLWRITER_SUPPORTED GTK_BASED_CONSUMER LEX_YACC_PARSER TSPPROVIDER BUILD_XMLRPC LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS AWK INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE RANLIB ac_ct_RANLIB AR CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP LIBOBJS PKG_CONFIG XML2_CONFIG GTK_CONFIG LEX LEXLIB LEX_OUTPUT_ROOT YACC XMLRPC_CONFIG CXX CXXFLAGS ac_ct_CXX DOXYGEN build build_cpu build_vendor build_os host host_cpu host_vendor host_os HOST_TARGET ARFLAGS LDLIBS TSP_BASE ENABLED_TSP_TARGET BB SHAREDLIB_ENABLED GL_OK GLUT_OK SCRIPT_BINDING TSPCONSUMER XML2_CONFIG_USER XMLWRITER_SUPPORTED GTK_BASED_CONSUMER LEX_YACC_PARSER TSPPROVIDER BUILD_XMLRPC APIDOC_GEN LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -863,6 +863,7 @@ Optional Features:
   --enable-blackboard          enable BlackBoard library and TSP BlackBoard Provider
   --enable-script-binding      enable scripting language binding of the TSP (this feature is ALPHA)
   --enable-cxxtsp              enable TSP C++ binding
+  --enable-apidoc          enable API doc generation with doxygen
   --enable-tsp-target-vxworks  enable VxWorks TSP target
   --enable-tsp-consumer        map TSP target to the TSP consumer
   --enable-tsp-provider        map TSP target to the TSP provider
@@ -5329,6 +5330,7 @@ fi
 ### End of BlackBoard Setup  ###
 ################################
 
+
 ###############################################
 # Scripting API for TSP
 # this is an alpha feature which will
@@ -5351,9 +5353,9 @@ else
 echo "$as_me:$LINENO: result: Disabled, won't be configured" >&5
 echo "${ECHO_T}Disabled, won't be configured" >&6
 fi
-################################
-### End of BlackBoard Setup  ###
-################################
+###########################################
+### End of Scripting API for TSP setup  ###
+###########################################
 
 ##########################
 # Setup C++ part of TSP
@@ -5755,6 +5757,87 @@ fi
 ### End of C++ Setup   ###
 ##########################
 
+################################
+# APIDOC generation
+################################
+# Check whether --enable-apidoc or --disable-apidoc was given.
+if test "${enable_apidoc+set}" = set; then
+  enableval="$enable_apidoc"
+  APIDOC_GEN=$enableval
+else
+  APIDOC_GEN="no"
+fi;
+echo "$as_me:$LINENO: checking API documentation generation using doxygen" >&5
+echo $ECHO_N "checking API documentation generation using doxygen... $ECHO_C" >&6
+if test "$APIDOC_GEN" = "yes"; then
+  echo "$as_me:$LINENO: result: Enabled, will be generated" >&5
+echo "${ECHO_T}Enabled, will be generated" >&6
+  # Extract the first word of "doxygen", so it can be a program name with args.
+set dummy doxygen; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_DOXYGEN+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$DOXYGEN"; then
+  ac_cv_prog_DOXYGEN="$DOXYGEN" # Let the user override the test.
+else
+  ac_prog_rejected=no
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    if test "$as_dir/$ac_word$ac_exec_ext" = "rej"; then
+       ac_prog_rejected=yes
+       continue
+     fi
+    ac_cv_prog_DOXYGEN="`which doxygen`"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+if test $ac_prog_rejected = yes; then
+  # We found a bogon in the path, so make sure we never use it.
+  set dummy $ac_cv_prog_DOXYGEN
+  shift
+  if test $# != 0; then
+    # We chose a different compiler from the bogus one.
+    # However, it has the same basename, so the bogon will be chosen
+    # first if we set DOXYGEN to just the basename; use the full file name.
+    shift
+    ac_cv_prog_DOXYGEN="$as_dir/$ac_word${1+' '}$@"
+  fi
+fi
+  test -z "$ac_cv_prog_DOXYGEN" && ac_cv_prog_DOXYGEN="notfound"
+fi
+fi
+DOXYGEN=$ac_cv_prog_DOXYGEN
+if test -n "$DOXYGEN"; then
+  echo "$as_me:$LINENO: result: $DOXYGEN" >&5
+echo "${ECHO_T}$DOXYGEN" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  if test "$DOXYGEN" = "notfound"; then
+     { echo "$as_me:$LINENO: WARNING: NOK: doxygen not found (update your path and rerun if present" >&5
+echo "$as_me: WARNING: NOK: doxygen not found (update your path and rerun if present" >&2;}
+     APIDOC_GEN="no"
+  fi
+else
+  echo "$as_me:$LINENO: result: Disabled, won't be generated" >&5
+echo "${ECHO_T}Disabled, won't be generated" >&6
+fi
+########################################
+### End of API Doc generation Setup  ###
+########################################
+
 #####################|##|############################|############
 # Get the system type from AC
 #####################|##|############################|############
@@ -6016,6 +6099,7 @@ done
 
 #
 #  Substitute Shell VARIABLES to OUTPUT VARIABLES
+
 
 
 
@@ -6720,6 +6804,7 @@ s,@XMLRPC_CONFIG@,$XMLRPC_CONFIG,;t t
 s,@CXX@,$CXX,;t t
 s,@CXXFLAGS@,$CXXFLAGS,;t t
 s,@ac_ct_CXX@,$ac_ct_CXX,;t t
+s,@DOXYGEN@,$DOXYGEN,;t t
 s,@build@,$build,;t t
 s,@build_cpu@,$build_cpu,;t t
 s,@build_vendor@,$build_vendor,;t t
@@ -6745,6 +6830,7 @@ s,@GTK_BASED_CONSUMER@,$GTK_BASED_CONSUMER,;t t
 s,@LEX_YACC_PARSER@,$LEX_YACC_PARSER,;t t
 s,@TSPPROVIDER@,$TSPPROVIDER,;t t
 s,@BUILD_XMLRPC@,$BUILD_XMLRPC,;t t
+s,@APIDOC_GEN@,$APIDOC_GEN,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
